# Generated by Django 3.2 on 2021-04-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
